using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Valve.VR;

public class PlayerController : MonoBehaviour
{
    public SteamVR_Action_Boolean TriggerClick;
    private SteamVR_Input_Sources inputSource;
 
    private void Start() {} //Monobehaviours without a Start function cannot be disabled in Editor, just FYI
 
    private void OnEnable()
    {
        TriggerClick.AddOnStateDownListener(Press, inputSource);
    }
 
    private void OnDisable()
    {
        TriggerClick.RemoveOnStateDownListener(Press, inputSource);
    }
 
    private void Press(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
    {
        Debug.Log("Button down!");
    }
}
